### ISSUE TITLE
Ex4 - uml abhaengiger java code

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#1]
Hier soll ein zur Aufgabe 4 des Praktikums geforderter Java Code zum UML Diagramm erstellt werden

**Comment by nikoliai** [comment]
1) Evt.sollten wir noch die Konstruktoren hinzufügen (?).  Auf dem UML Diagramm gibt es nichts, aber vielleicht hält man sie für etwas Selbstverständliches.. 
2) Bei manchen Assoziationen steht 0...*, bei den anderen 1 ...*.  Sollten sich denn die entsprechenden Klassenattribute im Quellcode von einander unterscheiden und wenn ja, wie?

**Comment by carnesirone** [comment]
zu 1. Ich denke das in diesem Fall kein Konstruktor gefordert war. Falls doch müsste es auch im UML-Diagramm enthalten sein

zu 2. Wird wohl bei der vollständigen Implementierung entschieden. Hier müsste man dann eine Abfrage einbauen, sodass das Array oder die Liste bei "1..*" nicht leer sein darf

Meiner Meinung nach passt das so. Hab die Wiki-Seite angelegt und verlinkt. Danke Olga!

**Comment by nikoliai** [comment]
Habe in fast allen Klassen Konstruktoren hinzugefügt, damit die Multiplizität bei bestimmten Attributen  korrekt dargestellt wird.

**Comment by nikoliai** [comment]
Wiki Eintrag upgedated. Der Source Code wurde in den src-Ordner zurück geschoben, weil Eclipse den sonst nicht als Source Code erkennt.

**Comment by carnesirone** [comment]
vielen dank. dann schließe ich den issue wieder
