### ISSUE TITLE
Pr3Ex6

### ISSUE THREAD

**Issue by nikoliai** [sweIhm-ws2018-19/skillproject-di-3#10]
Aufgabe 6: "Aktivitätsdiagramm erstellen"

**Comment by Plugsocket** [comment]
Die Implementierung ist soweit vollkommen in Ordnung. Zu Punkt 8 habe ich jedoch eine kleine Frage, müsste nicht hier nicht noch ein Objektknoten "Datenbank" hin ?  Es handelt sich nämlich um eine permanente Datenänderung und diese müsste doch im Rahmen eines Objektknotens irgendwo vermerkt werden.

**Comment by nikoliai** [comment]
Habe die Ein- bzw Ausgangsparameter an die richtige Stelle verschoben

**Comment by Plugsocket** [comment]
Alles klar, sollte soweit dann alles passen.
