### ISSUE TITLE
Pr3Ex9 - sequence diagramm

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#12]
Aufgabe 9: Sequenzdiagramm für eine Operation "drucken()" von Dokument1 aus Aufgabe 8 erstellen

**Comment by carnesirone** [comment]
Sequenzdiagramm wurde hinzugefügt.
Hier sind beide Fälle der Interpretation aus Aufgabe 8 enthalten.
Bitte um Kontrolle

**Comment by langehm** [comment]
Blöcke wurden zentriert über die gestrichelten Linien verschoben. Sonst alles ok.
