### ISSUE TITLE
Product Backlog im Github Project mit Github Issues erstellt

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#17]
Erstellen Sie einen Product Backlog für das gesamte Praktikumsprojekt. Den Product Backlog erstellen Sie unter Verwendung von Github Issues. 
Erstellen Sie ein 'Project' in Github und clicken Sie auf 'add column'. Diese Spalte nennen Sie 'Product Backlog'. Weitere Spalten in Ihrem Projekt sind 'Ready' (ready to be worked on), 'In Progress' (currently worked on) und  'Done'.

**Comment by carnesirone** [comment]
User Stories wurden erstellt, hiermit geschlossen.

**Comment by carnesirone** [comment]
Produkt Backlog und User Stories anhand geänderter Anforderungen angepasst.

**Comment by langehm** [comment]
Abgeschlossen
