### ISSUE TITLE
Beschreibung der User Stories

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#18]
Für jede User Story im Product Backlog erstellen Sie ein Github Issue. 
a) Tipps wie man gute User Stories schreibt: http://www.romanpichler.com/blog/10-tips-writing-good-user-stories/
b) Jede User Story hat einen Titel, eine Story, eine aussagekräftige Beschreibung und Akzeptanzkriterien. Gerne können auch Diagramme oder Abbildungen Teil der Beschreibung der User Story sein.

**Comment by langehm** [comment]
Klasse
