### ISSUE TITLE
Ex5 - objektdiagramm zur beschreibung

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#2]
Erstellen eines UML Objektdiagramms zur Beschreibung in Aufgabe 5

**Comment by Plugsocket** [comment]
Meiner Meinung nach müssten die Pfeile weg, da es sich, ausgehend vom Klassendiagramm, um eine Objektassoziation und nicht um eine Vererbung handelt.
Darüber hinaus werden, zumindest nach (Oestereich, Bernd; Analyse ..) im Objektdiagramm keine Multiplizitäten  verwendet, sondern nur die Art der Beziehung angeben, in unserem Bespiel "besitzt Adresse".

**Comment by Plugsocket** [comment]
Ich bin mal so frei und schlage eine mögliche weitere Lösung vor
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Objektdiagramm_Aufgabe5.xml#R7VlLb%2BM4DP41OaawLNtNjkn6mEMLFNMFdueoxootVLYyspxHf%2F1StuS3d7JN2lOKAI0oiqL4faRpZYJXyeFRkm38LELKJ64THib4buK6CDkB%2FNOSYynxZ14piCQLjVIteGUf1AgdI81ZSLOWohKCK7ZtC9ciTelatWRESrFvq20Eb%2B%2B6JRHtCV7XhPelf7NQxaV05t7W8h%2BURbHdGQXzcuaNrN8jKfLU7Ddx8ab4K6cTYm2Zg2YxCcW%2BIcL3E7ySQqjyW3JYUa5ja8NWrnsYma38ljRVpyxwywU7wnNz9B8kzZ4nKzxZrjincoIXMP9Is3WshQtvk6l3OB41%2FqujjVm2ZwknKYyWG5GqVzPjwHgdMx4%2BkaPItVOZgiDZ0TIWkn2APuEwhUAA01IZSriBtsY4XwkuwJe7VBQb1ItetTGzjaQZLHuxh0cd0TM5tBSfSKasg4Jzss3YW%2BGyXpgQGbF0KZQSiVGyB3xo%2BFPji5f92Bs4dlQqemiIDBaPVCRUySOo2FnLC5M3MzPc1ySsciRuENA3OBLD%2B6iyXGMPXwz8w1TAPSpMdeowmdA0JQkA7hRi2D74nWuCLp8hYWCaZYrKJmcqhR5JIA6qwFiKd9oBdQBnwlmUwpDTjV6mA8kgSxdGrMRWG9uSNUujp0LnzqslP02AtEjA2g0vUi1mYUhTTQOhiCJvFU23gqWqiKC%2FhA8cdOXc%2BBMfHF%2FBGNVj%2BGh1qVYihbMQViBOgVB7mqlBLrgnc8Fg7wanYW%2F1zsE%2B6GH%2FxGhG23XgRbIduSb%2FlyW%2Ff0Ly4wEC3M7OJ8DtYPLvhBzJ%2FIIe1zwfgD04Gfb%2FyPMhmC%2BR57NBmFOyjscq%2FLWqXxZt%2B6T%2BDrSR34N77ImNF4swhMqYXUv7V5R2jNulfai2o9kADZBdeBYPhqu7prgGfDzltYYezR%2ButX6QB%2F7JRBgv9oO4XyL9K5q2YY9JnqV50ij3lh9XTD%2BF6UBJ%2FzJM0fATfMs%2FBh7eyMWef03ci4Bsm%2BxvSdz%2BrYwGGU441KHl%2BlmukxrCeMX6Elgjx%2FtGsL0e2D3waBou9K1mjQ9IdLti4herxHZZNIyobdEgTLGIREr4fS09DVp6YOofbf3GwzMz%2FqW3uHGq8QuVDI6ru8fCC4i4POpFU%2BfGQchKfhVmEK4E3XWj%2FVUmcrk2ITC3U9BDRrQDrD7yKU3Y1JiVlBPFdu2r3iEIjaUXzc7GHZ3f7uWw22nRSrfNqubda8dQ1QQaQ1631ysP2zMEVCDHhprJnlGHXeS2m8%2F5bYegpcWarlXsTrs47JcrKERcmReGFpVtfdIT06x4GdD3y8jZHprFK4j0%2Fzdo59WHNrCw7yalWfCotFzqjRW7RloUbwajFUcXFZIrUTpULPg%2FBfAvPbibepd5V0AdWlSXfo1qNFiMLvCmgD9VjBpxHj3%2FH5O0cTp%2F4HRWdmbyBl47uCjAn0teH3VQmnd8uVDydh3u%2FaDzJ%2F15S%2F%2F8ZO%2FfKVyT%2FfPJHjgduPCXJTsM698VS%2BTrH2%2Fx%2Fb8%3D

**Comment by langehm** [comment]
Fertig bearbeitet. File hochgeladen.
