### ISSUE TITLE
Rezeptkategorien vorlesen

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#20]
Als User will ich das mir der Skill die vorhandenen Kategorien vorliest, um daraus eine auswählen zu können.

Akzeptanzkriterium:
* Vorlesen aller vorhandenen Kategorien

**Comment by Plugsocket** [comment]
Laut Moodle sollen wir noch ein Klassendiagramm oder Sequenzdiagramm zu jeder User-Story machen.

**Comment by langehm** [comment]
Diagram wurde angehängt. passt

**Comment by nikoliai** [comment]
Meiner Meinung nach fehlen auf deinem  Sequenzdiagramm  noch der User und Alexa. Eigentlich sollten sie auch da stehen, damit alle Abläufe des Use Cases vollständig und korrekt abgebildet werden (der User ist der Auslöser, Alexa nimmt seinen Input entgegen und leitet ihn an den Handler weiter).
Und ich bin mir nicht sicher, ob die speziellen Handler vom Stream Handler aufgerufen werden (oder direkt von Alexa) und wie die Response von speziellen Händlern zu Alexa zurückkommt.

**Comment by nikoliai** [comment]
Passt!
