### ISSUE TITLE
Rezept auswählen

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#21]
Als User will ich ein Rezept anhand eines Kriteriums auswählen.

Akzeptanzkriterien:
* Rückgabe des gewählten Rezepts
* Speichern des Rezepts

**Comment by carnesirone** [comment]
Bevor dieses Issue behandelt werden kann muss auf die Fertigstellung der Issues "Kategorie auswählen" und "Favorit auswählen" gewartet werden.

**Comment by nikoliai** [comment]
Du hast vergessen, den Intent ins JSON -File hinzuzufügen. Habe es aber bereits erledigt. Intent funktioniert.
