### ISSUE TITLE
Rezept favorisieren

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#22]
Als User will ich ein Rezept auswählen, um es zu bewerten.

Akzeptanzkriterium:
* Erfolgreiches Speichern eines Rezepts

**Comment by nikoliai** [comment]
![image](https://user-images.githubusercontent.com/43779042/49692404-90d05180-fb5a-11e8-941b-d86a608246ca.png)
JSON lässt sich nicht bilden. Bitte beheben.

**Comment by langehm** [comment]
Noch ein Fehler im Code. Nullpointer Zugriff wahrscheilich auf die SessionAttribute.

**Comment by langehm** [comment]
Rezept favorisieren funktioniert noch nicht da beim mergen ein Fehler aufgetreten ist. Dieser Fehler ist bereits auf dem Master behoben, allerdings noch nicht verschwunden für rezept favorisieren.

**Comment by Plugsocket** [comment]
Ein Rezept kann mit Hilfe der Eingabe des Namens des jeweiligen/ausgewählten Rezeptes zur Favoriten-Liste hinzugefügt werden.
