### ISSUE TITLE
Rezeptschritte vorlesen

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#24]
Als User will ich das mir der Skill die Schritte eines Rezepts vorliest.

Akzeptanzkriterium:
* Vorlesen der Schritte in richter Reihenfolge

**Comment by nikoliai** [comment]
Also es funktioniert soweit. Man muss aber die Intents sehr genau angeben - sonst verwechselt sie Alexa und geht in einen anderen Handler. Für den nächsten Sprint sollten wir ein issue erstellen, alle Ausdrücke zu "säubern", also für jeden Intent eindeutige und einzigartige Phrasen auszudenken.

**Comment by carnesirone** [comment]
Funktion funktioniert. Allerdings würde ich die Methode recipeToRead abändern.
Diese Funktionen könnten wir gleichzeitig nutzen und als savedRecipe umbennen. Somit kann jeder auf das derzeit ausgewählte Rezept zugreifen und handeln.

**Comment by carnesirone** [comment]
Funktioniert! Bitte noch testen und Sequenzdiagramm commiten.

**Comment by carnesirone** [comment]
Intent funktioniert und Diagramm ist vorhanden.
