### ISSUE TITLE
Timer-Funktion

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#25]
Als User will ich das mir der Skill die hinterlegte Wartezeit vermittelt.

Akzeptanzkriterium:
* Einhalten der Zeit

**Comment by nikoliai** [comment]
Es geht nicht nur um die Back-, sondern auch um die Kochzeit

**Comment by carnesirone** [comment]
Es wurde im Team beschlossen, dass diese Funktion für den Skill nicht notwendig ist.
