### ISSUE TITLE
Favoriten auswählen

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#26]
Als User will ich ein Rezept aus meiner Favoritenliste auswählen.

Akzeptanzkriterium:
* Rückgabe des gewählten Rezepts

**Comment by Plugsocket** [comment]
Ich bin mir leider nicht sicher ob hier die komplette User-Story abgearbeitet wurde, da die interne Methode "findByFavourite" in CookingBook nicht verändert wurde.

**Comment by Plugsocket** [comment]
Die Implementierung der Methode erfolgte innerhalb des IntentHandlers, daher ist die interne Methode "findByFavourite" irrelevant.
Passt von meiner Seite aus.

**Comment by Plugsocket** [comment]
Die Rezepte, welche in der Liste in der Favoriten enthalten sind werden vorgelesen, darauffolgend kann man eines dieser Rezepte auswähle. Passt daher von meiner Seite aus.

**Comment by nikoliai** [comment]
Bitte den von Alexa gesagten Text umformulieren. "Waehle einen deiner Favoriten fuer den naechsten Schritt aus" ist zu schwammig und zu ungenau. Es ist nicht klar, welchen "nächsten Schritt" man meint.  Bitte präzisieren, was die Person genau machen/sagen soll. Mein Vorschlag wäre so was wie: "Wähle das Rezept, das vorgelesen werden soll".

**Comment by nikoliai** [comment]
Bzw. "Waehle das Rezept, das vorgelesen werden soll. Sage zum beispiel: Ich moechte Schnitzel kochen".  Du kannst ein neues Rezept zu den Favoriten hinzufuegen. Sage dafuer "Rezept favorisieren". Dann wird der User gleich auf diese zwei Optionen hingewiesen.

**Comment by Plugsocket** [comment]
Der User wird darauf hingewiesen welche Rezepte sich in der Favoriten-Liste befinden, von dieser kann er dann sein Rezept via Name auswählen. 
Das vorlesen dieser Favoriten-Liste funktioniert einwandfrei.
