### ISSUE TITLE
Direkt eingeben

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#27]
Als User will ich ein Rezept mittels direkter Eingabe auswählen.

Akzeptanzkriterium:
* Rückgabe des gewählten Rezepts

**Comment by nikoliai** [comment]
Benötigte Händlers bearbeitet , JSON file dementsprechend angepasst, Methode mithilfe von JUNIT Tests getestet. Mit Alexa getestet. Alles funktioniert. Das einzige, was ich gemerkt habe, ist, dass Alexa bei ähnlichen Samples die Intents verwechselt und zum falschen Intent rüberkommt. Deswegen sollten wir die Samples möglichst unterschiedlich formulieren.

**Comment by carnesirone** [comment]
Soweit keine Einwände. Tests laufen. Diagramm scheint zu passen und der Intent wird auf dem Skill ausgeführt!
