### ISSUE TITLE
Kategorie auswählen

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#28]
Als User will ich ein Rezept anhand gegebener Kategorien auswählen.

Akzeptanzkriterium:
* Rückgabe des gewählten Rezepts

**Comment by Plugsocket** [comment]
Auf dem Branch Plugsocket kann die User-Story gereviewed werden.

**Comment by langehm** [comment]
Funktioniert jetzt zu jedem Zeitpunkt. passt
