### ISSUE TITLE
Personenzahl

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#29]
Als User will ich ein Rezept aufgrund abweichender Anzahl an Personen modifizieren, um eine angepasste Zutatenliste zu erhalten.

Akzeptanzkriterium:
* Rückgabe des korrekt modifizierten Rezepts

**Comment by Plugsocket** [comment]
Auf dem Branch Plugsocket kann die User-Story gereviewed werden.

**Comment by langehm** [comment]
Getestest. passt jetzt
