### ISSUE TITLE
Pr3Ex2

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#3]
Arbeitsblatt "Anwendungsfall-, Aktivitäts- und Sequenzdiagramme" - Aufgabe 2

**Comment by langehm** [comment]
Aufgabe frei zur Überprüfung

**Comment by nikoliai** [comment]
- Partition hinzugefügt
- Entscheidung und Zusammenführung  geändert ( war ein falsches Bild) 
- Conditions bei der Zusammenführung gelöscht
