### ISSUE TITLE
Menge

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#30]
Als User will ich ein Rezept aufgrund einer gegebenen Menge einer Zutat modifizieren, um eine angepasste Zutatenliste zu erhalten.

Akzeptanzkriterium:
* Rückgabe des korrekt modifizierten Rezepts

**Comment by carnesirone** [comment]
Nachdem ich nun mehrere Versuche gestartet habe die UserStory anständig zu implementieren, folgende Anmerkungen:
Bei der Abfrage über Alexa lässt sich zwar in einzelnen Schritten der Verlauf des Intent beeinflussen, jedoch steht man spätestens bei der Eingabe der zu änderten Menge vor einem Problem.
Die Zutat wird über einen String gelesen, kann aber in der Map nicht über den Key gefunden werden, da es sich hierbei um ein "Ingredient" handelt.
Auch ist es nicht möglich, die gesprochene Eingabe die als String importiert wird, in einen Integer zu casten. Dabei wird die gesprochene Zahl als Wort erkannt und ist somit nicht verwendbar.

Zur Lösung sollten wir uns überlegen, ob wir dieses Feature evlt. durch ein anderes ersetzen (zum Beispiel Zutatenliste vorlesen) oder komplett entfallen lassen (was allerdings den Umfang des Skills sehr minimieren würde).

Daher mein Vorschlag: Im Sprint-Review besprechen und ggf. ändern.

**Comment by gsocher** [comment]
Haben Sie sich den Slot Type AMAZON.NUMBER angesehen? https://developer.amazon.com/docs/custom-skills/slot-type-reference.html#number

**Comment by carnesirone** [comment]
Nachdem ich alle Versionen probiert habe...das Implementieren eines "SpeechletsV2" oder die Einführung von mehreren Intens zur Verwaltung dieses einen, war ich erfolglos bei der Suche dieser Möglichkeit-

Super. Danke.

**Comment by carnesirone** [comment]
Implementierung ist abgeschlossen. Einzig der cast von AMAZON.NUMBER zu einem verwertbaren Int funktioniert noch nicht. Alle Funktionalitäten wurden mit ExceptionHandlich abgesichert.

**Comment by nikoliai** [comment]
Exceptions funktionieren. Spracheingabe geht auch. Casting  von String in Integer muss noch gemacht werden.

**Comment by nikoliai** [comment]
Bitte die Anweisung umformulieren. Es ist nicht ganz klar, was man genau sagen soll (ob z.B. "Eis auf 500" oder "Eis auf 500 gramm" o.Ä.) Evtl. einen Beispielsatz hinzufügen. Zurzeit funktioniert der Intent auf dem Master Branch anscheinend nicht.

**Comment by carnesirone** [comment]
Funktioniert schon.
Allerdings muss bei der Eingabe in der Testkonsole das Wort einer Zahl z.B. "drei" statt 3 verwendet werden, da AMAZON.Number lediglich den String einer Zahl umwandelt, was bei der späteren Verwendung via Sprache automatisch funktioniert.

Beispielsatz zur Eingabe wird bereits ausgegeben: {Zutat} auf {Menge} anpassen
Hierzu erfolgt noch ein Vermerk im Wiki

**Comment by nikoliai** [comment]
{Zutat} auf {Menge}  ist kein Beispielsatz. Ich meinte ganz konkret, z.B. "Milch auf hundert anpassen".  Erstens ist das Wort "Menge" an sich doppeldeutig (geht es nur um die Zahl oder Zahl+Unit?). Es ist schon bei der Eingabe nicht klar, was genau erwartet wird. Des weiteren ist die benutzte Eingabeform ("Milch auf hundert anpassen") in der Alltagssprache nicht gebräuchlich und somit  nicht immer intutiv zu "generieren".   Man möchte automatisch auch Unit hinzufügen, so wie "Milch auf hundert gramm anpassen", wie man das in der Alltagssprache sagt. Und dann bekommt man als response, dass es unmöglich war. und das nervt. 
Somit ist purer Hinweis {Zutat} auf {Menge} aus meiner Sicht für den User nicht ausreichend. Ich bin nach wie vor der Meinung, dass hier noch ein konkretes Beispiel hinzugefügt werden soll.

**Comment by carnesirone** [comment]
Intent wurde angepasst und kann nun intuitiver verwendet werden.
Der Beispielsatz wurde auf "Ei auf drei Stueck anpassen" geändert.
Die Unit wird im Intent als Slot erkannt, im weiteren Verlauf jedoch nicht verwendet, da die Abfrage der Ingredients über deren Name läuft.

Bitte um Review.

**Comment by nikoliai** [comment]
Funktioniert super, vielen dank!
