### ISSUE TITLE
Lösungsideen der User Storys

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#34]
Stellen Sie für jede User Story Ihre Lösungsidee wenn möglich als UML Diagramm (z.B. UML Klassendiagramm oder UML Sequenzdiagramm) dar. Es kann manchmal sinnvoll sein, dass Sie die Lösungsidee zu mehreren User Stories in einem Diagramm zusammenfassen.

Verschieben Sie eine User Story, an der Sie arbeiten in Ihrem Project Board in die Spalte 'in Progress'.

**Comment by Plugsocket** [comment]
Eine weitere Idee ist es für die jeweiligen Kategorien Vegan, Vegetarisch sowie Fleisch neue Listen hinzuzufügen, da diese dann in eigenen Containern liegen und so besser erreichbar sind.

**Comment by carnesirone** [comment]
Laut Diagramm hat das Rezept bereits eine feste Kategorie.
Das sollte nacher das Filtern der gesamten Rezeptliste über die jewelige Kategorie erheblich erleichtern.
Zumal es dann einfacher ist, zusätzliche Kategorien hinzuzufügen, ohne das dafür noch eine weitere Liste erstellt werden muss. Die Methode zum Aufrufen der gefilterten Rezeptliste gibt dann eine Liste mit den Rezepten der Kategorie zurück, mit der man eine Auswahl treffen kann.

**Comment by Plugsocket** [comment]
Alles klar, dann würde ich quasi einen kleinen Suchalgorithmus basteln, der mir einmal durch die Liste iteriert und dabei alle Kategorie zutreffenden Rezepte ausfiltert und zurückgibt.

**Comment by carnesirone** [comment]
Wenn jemand Dinge zu Implementieren hat, die über die AWS Konsole laufen, kann er mich gerne kontaktieren. So lassen wir den Endpoint des Skills für alle Nutzer gleich und können die Frau Socher am Dienstag fragen, wie das nun mit der Gruppenverwaltung künftig laufen soll, dass scheint im Moment noch sehr komisch zu funktionieren. Den Zugriff auf die Alexa Developer Konsole müssen wir noch Regeln, wobei es hier erst mal noch nicht allzu viel ausmacht, wenn das über alle läuft und wir einen funktionierenden dann abgeben. Einwände?

**Comment by carnesirone** [comment]
Lösungsideen wurden besprochen und im Wiki vermerkt. Somit geschlossen.
