### ISSUE TITLE
Programmieren & Testen der User Storys

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#35]
Programmieren Sie Ihre User Story.
Erstellen Sie JUnit-Tests. JUnit-Tests stehen in einem Maven Projekt unter dem Verzeichnis:
"src/test/java" .Testen Sie automatisiert.
Fragen und Anmerkungen zu Ihrer User Story notieren Sie in Kommentaren des jeweiligen Github Issues.
Machen Sie häufige commits in Github.
Stellen Sie sicher, dass Ihr Projekt in travis-ci gebaut werden kann (siehe https://moodle.hm.edu/mod/page/view.php?id=349664).

Kennzeichnen Sie eine User Story mit 'ready for review', wenn das verantwortliche Teammitglied sicher gestellt hat, dass alle Akzeptanzkriterien erfüllt sind. Ein weiteres Teammitglied überprüft die Akzeptanzkritieren und lässt sich den Code erklären. Nach dem Code Review und möglichen Änderungen, die sich aus dem Code Review ergeben, wird die User Story auf dem Project Board in die Spalte Done verschoben.

**Comment by Plugsocket** [comment]
Das Programm wirft bei mir eine Nullpointerexception, wenn es versucht das Kochbuch mit Rezepten zu füllen und zwar genau an der Stelle in welcher die erste Zutat übergeben werden soll.

**Comment by carnesirone** [comment]
User Stories wurden 3 von 4 programmiert und getestet. Nähere Infos wurden im Wiki vermerkt. Somit geschlossen.
