### ISSUE TITLE
Handler anpassen

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#37]
Anpassen der lieblingsfarbe Handler auf unseren Alexa Skill

**Comment by carnesirone** [comment]
Handler für Begrüßung wurde angepasst und der Intent "TellMeCategories" hinzugefügt.
Skill lässt sich vorerst noch über "lieblingsfarbe" öffnen.
Man kann nach der Begrüßung beispielsweise, "sag mir alle Kategorien" sagen und Alexa ließt einem dann alle derzeit angelegten Enums aus "Category" vor.

**Comment by carnesirone** [comment]
Habe es noch nicht hinbekommen euch als Teammitglieder hinzuzufügen.
Wer den Skill testen möchte muss in der Alexa Developer Konsole das neue JSON File einbinden.
In der AWS -> Lambda die neue *.jar einbinden und beim Textfeld "Handler": main.java.verkocht.VerkochtStreamHandler eintragen. Mit der invocation "lieblingsfarbe" loslegen

**Comment by carnesirone** [comment]
Handler wurden nun soweit alle hinzugefügt.
Alles weitere wie oben bereits erklärt.
Invocation und Skill Name lautet nun auch "Verkocht"

**Comment by langehm** [comment]
Aufrufe von Intents funktionieren. Rückgang zum Hauptmenü folgt noch. Klasse

**Comment by langehm** [comment]
Rückgang zum Hauptmenü funktioniert. Perfekt
