### ISSUE TITLE
Vorlagenrezepte ergänzen

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#38]
Ergänzen der vordefinierten Rezepte bzgl. Schritte usw.

**Comment by carnesirone** [comment]
Dieses Issue ist meiner Meinung nach nun doch Teil eines späteren Sprints.
Im nächsten Sprint-Planning gemeinsam die Priorität anpassen.

**Comment by nikoliai** [comment]
Rezeptenvorlagen ergänzt. Die dazu benötigten Attribute ergänzt. Der Konstruktor  dementsprechend bearbeitet.

**Comment by carnesirone** [comment]
Vorlagen werden bei der Auswahl erkannt. Ob noch Änderungen vorzunehmen sind, sobald die UserStory "Rezeptschritte vorlesen" erstellt wird, müssen wir im Verlauf sehen.
Danke!
