### ISSUE TITLE
Optimierung der Responsesätze

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#39]
Klasse für die ganzen Sätze die Alexa sprechen soll, können mit Keywords angesprochen werden können.
Dies macht alle Klassen übersichlicher  und besser lessbar. Keywords wie z.B.: Keywords für Hashmaps können da auch rein.

**Comment by carnesirone** [comment]
Responsesätze sind auf meinem Branch angepasst und können nun in den Intents verwendet werden.
Bitte um Review.
