### ISSUE TITLE
Pr3Ex7

### ISSUE THREAD

**Issue by langehm** [sweIhm-ws2018-19/skillproject-di-3#4]
Arbeitsblatt "Anwendungsfall-, Aktivitäts- und Sequenzdiagramme" - Aufgabe 7

**Comment by langehm** [comment]
Aufgabe frei zur Überprüfung

**Comment by nikoliai** [comment]
Habe Multiplizitäten und Visibility gelöscht, da sie aus dem Sequenzdiagramm nicht ausgelesen werden können. Rolle schreibt man neben der Klasse, deren Rolle beschrieben ist - war letztes Mal unser Fehler (habe geändert). Pfeile bei Assoziationen müssen offen sein (geändert).
