### ISSUE TITLE
Anwendungsfalldiagramm aktualisieren

### ISSUE THREAD

**Issue by Plugsocket** [sweIhm-ws2018-19/skillproject-di-3#45]
Das Anwendungsfalldiagramm soll in einer neuen Version den aktuellen Stand(Progress) darstellen.

**Comment by langehm** [comment]
Angesprochene Änderung wurde vorgenommen. Passt

**Comment by langehm** [comment]
Anpassungen bezüglich des neuen Anwendungsfalldiagramm werden noch vorgenommen

**Comment by langehm** [comment]
Falschen Issue wieder eröffnet.
