### ISSUE TITLE
Zutatenliste vorlesen

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#56]
Es wird eine Funktion benötigt, die die Zutatenliste des gewählten Rezepts vorliest.

Diese Funktion ersetzt die Eingangs definierte Timer-Funktion als Ersatz.

**Comment by nikoliai** [comment]
![image](https://user-images.githubusercontent.com/43779042/50001988-ec596f80-ff9e-11e8-891f-bc6881e2fb18.png)
beim Vorlesen der Zutatenliste wird jedesmal das Wort "Minus" ausgesprochen

**Comment by carnesirone** [comment]
Fehler wurde entfernt. Bitte um Review.

**Comment by nikoliai** [comment]
Jetzt passt alles. Vielen Dank).
