### ISSUE TITLE
Erstellung eines rudimentären Hauptmenüs

### ISSUE THREAD

**Issue by carnesirone** [sweIhm-ws2018-19/skillproject-di-3#57]
Es soll für den Skill ein Hauptmenü erstellt werden, damit der User die Option hat, einen Vorgang abzubrechen, ohne das die Session vollständig beendet wird.

**Comment by nikoliai** [comment]
Ich habe ins Hauptmenü nur große Kategorien hinzugefügt, weil das Vorlesen der Menüoptionen sonst zu lange und zu langweilig wird. Die Unterkategorien von einer bestimmten Oberkategorie werden in dem jeweiligen Intent vorgelesen.
