### ISSUE TITLE
Pr3Ex1

### ISSUE THREAD

**Issue by nikoliai** [sweIhm-ws2018-19/skillproject-di-3#6]
Aufgabe 1. Anwendungsfalldiagramm "Funktionalität einer Kamera"

**Comment by Plugsocket** [comment]
Ich habe die Datei geändert, da versehentlich zwei mal der Anwendungsfall "Foto aufnehmen" vorhanden war und der Anwendungsfall "Fotoalbum ansehen" fehlte.

**Comment by nikoliai** [comment]
Habe die Linien ein bisschen schöner gemacht.

**Comment by Plugsocket** [comment]
Passt
